version: '3'
services:
  database:
    image: mariadb
    container_name: database
    volumes:
      - ./_database:/var/lib/mysql
    expose:
      - "3306"
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "admin"
      MYSQL_DATABASE: database
      MYSQL_USER: root
      MYSQL_PASSWORD: admin
      TZ: Europe/Paris
    restart: always

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - "7070:80"
    environment:
      - PMA_ARBITRARY=1
    depends_on:
      - database

  frontend:
    ports:
      - "80:80"
    build:
      context: ./frontend
      dockerfile: 'Dockerfile'
    volumes:
      - ./frontend:/app/src
    restart: always

  backend:
    ports:
      - "3000:3000"
    build:
      context: ./backend
      dockerfile: 'Dockerfile'
    depends_on:
      - database
    environment:
      NODE_ENV: production
    restart: always